version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - additionalalias
  - dangerousfiles
  - Entra
  - mailaddress
  - mailalias
  - Organisational
  - spamrules
ignoreWords: []
import: []
